// Navigation 
// Nests UL elements generated by nested-nav.xsl into their corresponding parent LI elements
// Words with production_root, root-relative, and absolute links
// Requires jQuery

// Last Updated 2/18/2014
// Optimized; corrected for '?' appended via tag manager 6/5/2024 - LHW

$(function(){

	// if not using param-expose.xsl, replace with hardcoded values
	var $domain = OUC.globalProps['domain']
	var $currentPage = $domain + OUC.globalProps['path'] /* window.location */
	var $extension = OUC.globalProps['extension'] /* .html, .aspx, .php, etc */
	var $indexFile = OUC.globalProps['index-file'] /* default, index etc */

	// if the http root is not the same as domain
	var $trueHTTP = $domain


	// function to open directory
	var openDirect = function(link) {
		//link.removeClass('style');
		link.attr('aria-expanded', 'true');
		//link.siblings('div').addClass('show');
	}


	// function to open all parent directories
	// optimized 2024-06-05
    var openParentDirect = function(link) {
        // target all parent divs
        var $parentDivs = link.parentsUntil('.side-nav__list', 'ul');
        $parentDivs.each(function() {
            var $this = $(this);
            $this.attr('aria-expanded', 'true').css('display', 'block');
            $this.siblings('div').find('button.side-nav__trigger').attr('aria-expanded', 'true');
            $this.siblings('a').removeClass('collapsed').attr('aria-expanded', 'true');
        });
    };


	// Expand left nav to current page 
	$('nav.side-nav.component ul li a').each(function() {
		var $link = $(this).attr('href');

		// Remove appended '?' from comparison if present
		if ($link.endsWith('?')) {
			$link = $link.slice(0, -1);
		}

		// Accommodate directory URLs by adding index file
		if (!$link.includes($extension)) {
			$link += $indexFile + '.' + $extension;
		}

		// variable to obtain data-href attribute from index links
		var $indexLink = $(this).attr('data-href');

		if (!$currentPage.includes($extension)) {
			$currentPage += $indexFile + '.' + $extension;
		}

		// check if link matches current page
		if ($currentPage === $link || $trueHTTP + $link === $currentPage || $currentPage.includes($indexLink)) {
			$(this).addClass('menu-secondary--active');

			// check if link is start of directory
			if ($(this).attr('data-toggle')) {
				openDirect($(this));
			}

			if ($(this).parent().attr('id') !== 'side-nav-accordion') {
				openParentDirect($(this));
			}

			// break iteration after match found. do not falsify.
			return; 
		}
	});

}); // end function