// Navigation 
// Nests UL elements generated by nested-nav.xsl into their corresponding parent LI elements
// Words with production_root, root-relative, and absolute links
// Requires jQuery

// Last Updated 2/18/2014

$(function(){

	// if not using param-expose.xsl, replace with hardcoded values
	var $domain = OUC.globalProps['domain']
	var $currentPage = $domain + OUC.globalProps['path'] /* window.location */
	var $extension = OUC.globalProps['extension'] 
	
	/* .html, .aspx, .php, etc */
	var $indexFile = OUC.globalProps['index-file'] /* default, index etc */

	// if the http root is not the same as domain
	var $trueHTTP = $domain


	// function to open directory

	var openDirect = function(link) {
		link.removeClass('collapsed');
		link.attr('aria-expanded', 'true');
		link.siblings('div').addClass('show');
	}


	// function to open all parent directories
	var openParentDirect = function(link) {

		// target all parent divs
		$parentDivs = link.parentsUntil('#side-nav-accordion', 'div');

		$parentDivs.addClass('show');

		//target all a tags
		$parentDivs.siblings('a').removeClass('collapsed');
		$parentDivs.siblings('a').attr('aria-expanded', 'true');
	}


	// FIND ACTIVE LINK 

	$('ul[id="side-nav-accordion"] li a').each(function(index, anchorTag){

		$link =  $(this).attr('href');

		//variable to obtain overview link
		if ($link.indexOf($extension) == -1)
		{
			$link = $link + $indexFile + '.' + $extension;

		}
		


		// variable to obtain data-href attribute from index links
		var $indexLink = $(this).attr('data-href');

		if ( $currentPage.indexOf($extension) == -1)
		{
			$currentPage = $currentPage + $indexFile + index;

		}





		// check if link matches current page
		if ($currentPage == $link || $trueHTTP+$link == $currentPage || $currentPage.includes($indexLink))
		{

			$(this).parent().addClass('menu-item--active-trail')
			$(this).parents('.menu-item--expanded').addClass('menu-item--active-trail menu-item--open')
			

			// check if link is start of directory
			if ($(this).attr('data-toggle')) {
				openDirect($(this));
			}

			if ($(this).parent().attr('id') != 'side-nav-accordion') {
				openParentDirect($(this));
			}

			// break out of the loop
// 			return false
		}

	});
	
	//Find active link in main nav
	$('nav[id="main-menu"] ul[class="menu"] li a').each(function(index, anchorTag){

		$link =  $(this).attr('href');
// console.log($link);
		//variable to obtain overview link
		if ($link.indexOf($extension) == -1)
		{
			$link = $link + $indexFile + '.' + $extension;

		}
		


		// variable to obtain data-href attribute from index links
		var $indexLink = $(this).attr('data-href');

		if ( $currentPage.indexOf($extension) == -1)
		{
			$currentPage = $currentPage + $indexFile + index;

		}





		// check if link matches current page
		if ($currentPage == $link || $trueHTTP+$link == $currentPage || $currentPage.includes($indexLink))
		{

			$(this).parent().addClass('menu-item--active-trail')
			console.log($link);
			
			

			// check if link is start of directory
			if ($(this).attr('data-toggle')) {
				openDirect($(this));
			}

			if ($(this).parent().attr('id') != 'side-nav-accordion') {
				openParentDirect($(this));
			}

			// break out of the loop
// 			return false
		}

	});
	



}); // end function